name: Main build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Tests
        run: npm run cypress:ci
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

      - name: Build
        run: npm run build
