name: Pull Request Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Tests
        run: npm run cypress:ci
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

      - name: Build
        run: npm run build
